apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-feed
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
      - image: zepol1357/udagram-api-feed
        name: api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always    
